export {
  Pagination,
  PaginationButton,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationNextButton,
  PaginationPrevious,
  PaginationPreviousButton,
  type PaginationButtonProps,
  type PaginationContentProps,
  type PaginationEllipsisProps,
  type PaginationItemProps,
  type PaginationLinkProps,
  type PaginationNextButtonProps,
  type PaginationNextProps,
  type PaginationPreviousButtonProps,
  type PaginationPreviousProps,
  type PaginationProps,
} from './pagination.js';
